from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    ProjectClass,
)


CONFIG = (
    BuildingType.RECREATION,
    "recreation_center",
    BuildingConfig(
        dealshield_tile_profile="recreation_recreation_center_v1",
        scope_items_profile="recreation_recreation_center_structural_v1",
        display_name="Recreation Center",
        base_cost_per_sf=215,
        cost_range=(190, 240),
        equipment_cost_per_sf=20,
        typical_floors=1,
        trades=TradeBreakdown(
            structural=0.27,
            mechanical=0.24,
            electrical=0.13,
            plumbing=0.14,
            finishes=0.22,
        ),
        soft_costs=SoftCosts(
            design_fees=0.06,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.075,
            testing=0.008,
            construction_management=0.03,
            startup=0.012,
        ),
        ownership_types={
            OwnershipType.GOVERNMENT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.038,
                equity_ratio=0.20,
                grants_ratio=0.05,
                target_dscr=1.15,
                target_roi=0.0,
            ),
            OwnershipType.NON_PROFIT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.045,
                equity_ratio=0.15,
                philanthropy_ratio=0.10,
                grants_ratio=0.10,
                target_dscr=1.10,
                target_roi=0.0,
            ),
        },
        nlp=NLPConfig(
            keywords=[
                "rec center",
                "recreation center",
                "community recreation",
                "activity center",
                "parks and rec",
                "leisure center",
            ],
            priority=44,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.92,
            "Memphis": 0.90,
            "New York": 1.35,
            "San Francisco": 1.40,
            "Chicago": 1.18,
            "Miami": 1.08,
        },
        special_features={
            "gymnasium": 30,
            "game_room": 15,
            "craft_room": 12,
            "dance_studio": 20,
            "outdoor_courts": 25,
        },
        base_revenue_per_sf_annual=35,
        occupancy_rate_base=0.70,
        occupancy_rate_premium=0.80,
        operating_margin_base=0.12,
        operating_margin_premium=0.20,
    ),
)
