from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    ProjectClass,
)


CONFIG = (
    BuildingType.HOSPITALITY,
    "full_service_hotel",
    BuildingConfig(
        display_name="Full Service Hotel",
        base_cost_per_sf=325,
        cost_range=(275, 375),
        scope_items_profile="hospitality_full_service_hotel_structural_v1",
        dealshield_tile_profile="hospitality_full_service_hotel_v1",
        equipment_cost_per_sf=45,  # FF&E
        typical_floors=8,
        trades=TradeBreakdown(
            structural=0.24,
            mechanical=0.26,
            electrical=0.14,
            plumbing=0.16,
            finishes=0.20,
        ),
        soft_costs=SoftCosts(
            design_fees=0.07,
            permits=0.025,
            legal=0.02,
            financing=0.035,
            contingency=0.09,
            testing=0.01,
            construction_management=0.035,
            startup=0.02,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.065,
                equity_ratio=0.35,
                target_dscr=1.30,
                target_roi=0.11,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "hotel",
                "full service hotel",
                "convention hotel",
                "resort hotel",
                "luxury hotel",
            ],
            priority=19,
            incompatible_classes=[ProjectClass.TENANT_IMPROVEMENT],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.95,
            "Memphis": 0.93,
            "New York": 1.45,
            "San Francisco": 1.50,
            "Chicago": 1.25,
            "Miami": 1.20,
        },
        special_features={
            "ballroom": 50,
            "restaurant": 75,
            "spa": 60,
            "conference_center": 45,
            "rooftop_bar": 55,
        },
        base_revenue_per_sf_annual=80,
        base_revenue_per_room_annual=120000,
        rooms_per_sf=0.002,
        occupancy_rate_base=0.75,
        occupancy_rate_premium=0.82,
        operating_margin_base=0.30,
        operating_margin_premium=0.38,
        labor_cost_ratio=0.37,
        food_cost_ratio=0.10,
        management_fee_ratio=0.03,
        utility_cost_ratio=0.06,
        maintenance_cost_ratio=0.04,
        insurance_cost_ratio=0.02,
        property_tax_ratio=0.10,
        marketing_ratio=0.08,
        reserves_ratio=0.04,
        franchise_fee_ratio=0.06,
    ),
)
