from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    ProjectClass,
)


CONFIG = (
    BuildingType.HOSPITALITY,
    "limited_service_hotel",
    BuildingConfig(
        display_name="Select Service Hotel",
        base_cost_per_sf=205,
        cost_range=(190, 230),
        scope_items_profile="hospitality_limited_service_hotel_structural_v1",
        equipment_cost_per_sf=28,
        typical_floors=5,
        trades=TradeBreakdown(
            structural=0.26,
            mechanical=0.24,
            electrical=0.13,
            plumbing=0.17,
            finishes=0.20,
        ),
        soft_costs=SoftCosts(
            design_fees=0.05,
            permits=0.02,
            legal=0.015,
            financing=0.03,
            contingency=0.07,
            testing=0.008,
            construction_management=0.025,
            startup=0.015,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.062,
                equity_ratio=0.30,
                target_dscr=1.25,
                target_roi=0.12,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "limited service",
                "select service",
                "express hotel",
                "budget hotel",
                "economy hotel",
            ],
            priority=20,
            incompatible_classes=[ProjectClass.TENANT_IMPROVEMENT],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.93,
            "Memphis": 0.91,
            "New York": 1.40,
            "San Francisco": 1.45,
            "Chicago": 1.20,
            "Miami": 1.15,
        },
        special_features={
            "breakfast_area": 20,
            "fitness_center": 15,
            "business_center": 10,
            "pool": 25,
        },
        base_revenue_per_sf_annual=52,
        base_revenue_per_room_annual=50000,
        rooms_per_sf=1.0 / 600.0,
        occupancy_rate_base=0.72,
        occupancy_rate_premium=0.80,
        operating_margin_base=0.37,
        operating_margin_premium=0.42,
        base_adr_by_market={
            "primary": 195.0,
            "secondary": 180.0,
            "tertiary": 165.0,
        },
        base_occupancy_by_market={
            "primary": 0.72,
            "secondary": 0.68,
            "tertiary": 0.64,
        },
        expense_percentages={
            "staffing_pct": 0.30,
            "utilities_ops_pct": 0.14,
            "sales_marketing_gna_pct": 0.09,
            "management_fee_pct": 0.03,
            "franchise_fee_pct": 0.07,
            "ffe_reserve_pct": 0.04,
        },
        development_cost_per_sf_by_finish={
            "standard": 190.0,
            "premium": 220.0,
        },
        cap_rate_defaults={
            "low": 0.070,
            "base": 0.075,
            "high": 0.085,
        },
        yield_on_cost_hurdle=0.095,
        dscr_target=1.38,
        labor_cost_ratio=0.24,
        food_cost_ratio=0.03,
        management_fee_ratio=0.03,
        utility_cost_ratio=0.12,
        maintenance_cost_ratio=0.05,
        insurance_cost_ratio=0.02,
        property_tax_ratio=0.10,
        marketing_ratio=0.08,
        reserves_ratio=0.05,
        franchise_fee_ratio=0.05,
    ),
)
