from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    OFFICE_UNDERWRITING_CONFIG,
)


CONFIG = (
    BuildingType.OFFICE,
    "class_b",
    BuildingConfig(
        display_name="Class B Office",
        base_cost_per_sf=175,
        cost_range=(150, 200),
        equipment_cost_per_sf=10,
        typical_floors=5,
        trades=TradeBreakdown(
            structural=0.28,
            mechanical=0.22,
            electrical=0.14,
            plumbing=0.11,
            finishes=0.25,
        ),
        soft_costs=SoftCosts(
            design_fees=0.05,
            permits=0.02,
            legal=0.012,
            financing=0.025,
            contingency=0.07,
            testing=0.008,
            construction_management=0.025,
            startup=0.008,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.72,
                debt_rate=0.062,
                equity_ratio=0.28,
                target_dscr=1.20,
                target_roi=0.09,
                amort_years=25,
                loan_term_years=10,
                interest_only_months=0,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "office",
                "office building",
                "class b",
                "commercial office",
                "professional building",
            ],
            priority=9,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.94,
            "Memphis": 0.90,
            "New York": 1.40,
            "San Francisco": 1.45,
        },
        special_features={
            "fitness_center": {
                "basis": "AREA_SHARE_GSF",
                "value": 30,
                "area_share_of_gsf": 0.015,
            },
            "cafeteria": {
                "basis": "AREA_SHARE_GSF",
                "value": 25,
                "area_share_of_gsf": 0.03,
            },
            "conference_room": {
                "basis": "AREA_SHARE_GSF",
                "value": 20,
                "area_share_of_gsf": 0.012,
            },
            "surface_parking": {
                "basis": "COUNT_BASED",
                "value": 5000,
                "count_override_keys": [
                    "surface_parking_space_count",
                    "parking_space_count",
                    "parking_stall_count",
                    "stall_count",
                    "space_count",
                ],
                "default_count_bands": [
                    {"label": "small_office", "max_square_footage": 50000, "count": 150},
                    {"label": "mid_office", "max_square_footage": 100000, "count": 300},
                    {"label": "large_office", "max_square_footage": 200000, "count": 500},
                    {"label": "campus_office", "count": 700},
                ],
                "unit_label": "space",
            },
            "storage_space": {
                "basis": "AREA_SHARE_GSF",
                "value": 10,
                "area_share_of_gsf": 0.05,
            },
            "security_desk": {
                "basis": "COUNT_BASED",
                "value": 15000,
                "count": 1,
                "count_override_keys": [
                    "security_desk_count",
                    "security_station_count",
                    "desk_count",
                ],
                "unit_label": "desk",
            },
        },
        special_feature_pricing_statuses={
            "fitness_center": "incremental",
            "cafeteria": "incremental",
            "conference_room": "incremental",
            "surface_parking": "incremental",
            "storage_space": "incremental",
            "security_desk": "incremental",
        },
        base_revenue_per_sf_annual=28,
        occupancy_rate_base=0.85,
        occupancy_rate_premium=0.88,
        operating_margin_base=0.39,
        operating_margin_premium=0.43,
        financial_metrics=OFFICE_UNDERWRITING_CONFIG["class_b"],
        dealshield_tile_profile="office_class_b_v1",
        scope_items_profile="office_class_b_structural_v1",
        utility_cost_ratio=0.10,
        property_tax_ratio=0.14,
        insurance_cost_ratio=0.02,
        maintenance_cost_ratio=0.08,
        management_fee_ratio=0.04,
        janitorial_ratio=0.03,
        security_ratio=0.01,
        reserves_ratio=0.03,
    ),
)
