from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    OFFICE_UNDERWRITING_CONFIG,
)


CONFIG = (
    BuildingType.OFFICE,
    "class_a",
    BuildingConfig(
        display_name="Class A Office",
        base_cost_per_sf=475,
        cost_range=(440, 510),
        equipment_cost_per_sf=15,
        typical_floors=10,
        trades=TradeBreakdown(
            structural=0.25,
            mechanical=0.25,
            electrical=0.15,
            plumbing=0.10,
            finishes=0.25,
        ),
        soft_costs=SoftCosts(
            design_fees=0.05,
            permits=0.02,
            legal=0.012,
            financing=0.03,
            contingency=0.075,
            testing=0.008,
            construction_management=0.035,
            startup=0.01,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.06,
                equity_ratio=0.25,
                target_dscr=1.25,
                target_roi=0.08,
                amort_years=25,
                loan_term_years=10,
                interest_only_months=0,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "class a office",
                "corporate headquarters",
                "tower",
                "high-rise office",
                "premium office",
            ],
            priority=8,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.95,
            "Memphis": 0.92,
            "New York": 1.45,
            "San Francisco": 1.50,
            "Chicago": 1.25,
        },
        special_features={
            "fitness_center": {
                "basis": "AREA_SHARE_GSF",
                "value": 35,
                "area_share_of_gsf": 0.02,
            },
            "cafeteria": {
                "basis": "AREA_SHARE_GSF",
                "value": 30,
                "area_share_of_gsf": 0.05,
            },
            "conference_center": {
                "basis": "AREA_SHARE_GSF",
                "value": 40,
                "area_share_of_gsf": 0.03,
            },
            "structured_parking": {
                "basis": "AREA_SHARE_GSF",
                "value": 45,
                "area_share_of_gsf": 0.24,
                "trade_allocation": {
                    "structural": 0.70,
                    "mechanical": 0.08,
                    "electrical": 0.10,
                    "plumbing": 0.04,
                    "finishes": 0.08,
                },
            },
            "green_roof": {
                "basis": "AREA_SHARE_GSF",
                "value": 35,
                "area_share_of_gsf": 0.03,
            },
            "outdoor_terrace": {
                "basis": "AREA_SHARE_GSF",
                "value": 25,
                "area_share_of_gsf": 0.02,
            },
            "executive_floor": {
                "basis": "AREA_SHARE_GSF",
                "value": 45,
                "area_share_of_gsf": 0.10,
            },
            "data_center": {
                "basis": "AREA_SHARE_GSF",
                "value": 55,
                "area_share_of_gsf": 0.015,
            },
            "concierge": {
                "basis": "COUNT_BASED",
                "value": 20000,
                "count": 1,
                "count_override_keys": [
                    "concierge_desk_count",
                    "concierge_count",
                    "lobby_desk_count",
                ],
                "unit_label": "desk",
            },
        },
        special_feature_pricing_statuses={
            "fitness_center": "incremental",
            "cafeteria": "incremental",
            "conference_center": "incremental",
            "structured_parking": "incremental",
            "green_roof": "incremental",
            "outdoor_terrace": "incremental",
            "executive_floor": "incremental",
            "data_center": "incremental",
            "concierge": "incremental",
        },
        base_revenue_per_sf_annual=41.0,
        occupancy_rate_base=0.92,
        occupancy_rate_premium=0.95,
        operating_margin_base=0.48,
        operating_margin_premium=0.52,
        operating_expense_per_sf=11.0,
        cam_charges_per_sf=7.0,
        staffing_pct_property_mgmt=0.06,
        staffing_pct_maintenance=0.12,
        market_cap_rate=0.06,
        financial_metrics=OFFICE_UNDERWRITING_CONFIG["class_a"],
        dealshield_tile_profile="office_class_a_v1",
        scope_items_profile="office_class_a_structural_v1",
        utility_cost_ratio=0.08,
        property_tax_ratio=0.12,
        insurance_cost_ratio=0.02,
        maintenance_cost_ratio=0.06,
        management_fee_ratio=0.03,
        janitorial_ratio=0.04,
        security_ratio=0.02,
        reserves_ratio=0.02,
    ),
)
