from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    OFFICE_UNDERWRITING_CONFIG,
)


CONFIG = (
    BuildingType.OFFICE,
    "class_a",
    BuildingConfig(
        display_name="Class A Office",
        base_cost_per_sf=475,
        cost_range=(440, 510),
        equipment_cost_per_sf=15,
        typical_floors=10,
        trades=TradeBreakdown(
            structural=0.25,
            mechanical=0.25,
            electrical=0.15,
            plumbing=0.10,
            finishes=0.25,
        ),
        soft_costs=SoftCosts(
            design_fees=0.05,
            permits=0.02,
            legal=0.012,
            financing=0.03,
            contingency=0.075,
            testing=0.008,
            construction_management=0.035,
            startup=0.01,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.06,
                equity_ratio=0.25,
                target_dscr=1.25,
                target_roi=0.08,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "class a office",
                "corporate headquarters",
                "tower",
                "high-rise office",
                "premium office",
            ],
            priority=8,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.95,
            "Memphis": 0.92,
            "New York": 1.45,
            "San Francisco": 1.50,
            "Chicago": 1.25,
        },
        special_features={
            "fitness_center": 35,
            "cafeteria": 30,
            "conference_center": 40,
            "structured_parking": 45,
            "green_roof": 35,
            "outdoor_terrace": 25,
            "executive_floor": 45,
            "data_center": 55,
            "concierge": 20,
        },
        base_revenue_per_sf_annual=41.0,
        occupancy_rate_base=0.92,
        occupancy_rate_premium=0.95,
        operating_margin_base=0.48,
        operating_margin_premium=0.52,
        operating_expense_per_sf=11.0,
        cam_charges_per_sf=7.0,
        staffing_pct_property_mgmt=0.06,
        staffing_pct_maintenance=0.12,
        market_cap_rate=0.06,
        financial_metrics=OFFICE_UNDERWRITING_CONFIG["class_a"],
        utility_cost_ratio=0.08,
        property_tax_ratio=0.12,
        insurance_cost_ratio=0.02,
        maintenance_cost_ratio=0.06,
        management_fee_ratio=0.03,
        janitorial_ratio=0.04,
        security_ratio=0.02,
        reserves_ratio=0.02,
    ),
)
