from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    ProjectClass,
)


CONFIG = (
    BuildingType.EDUCATIONAL,
    "middle_school",
    BuildingConfig(
        display_name="Middle School",
        base_cost_per_sf=295,
        cost_range=(270, 320),
        equipment_cost_per_sf=30,
        typical_floors=2,
        trades=TradeBreakdown(
            structural=0.27,
            mechanical=0.25,
            electrical=0.14,
            plumbing=0.15,
            finishes=0.19,
        ),
        soft_costs=SoftCosts(
            design_fees=0.07,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.01,
            construction_management=0.035,
            startup=0.012,
        ),
        ownership_types={
            OwnershipType.GOVERNMENT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.04,
                equity_ratio=0.20,
                grants_ratio=0.15,
                target_dscr=1.15,
                target_roi=0.0,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "middle school",
                "junior high",
                "intermediate school",
                "grades 6-8",
                "grades 7-9",
            ],
            priority=2,
            incompatible_classes=[ProjectClass.TENANT_IMPROVEMENT],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.94,
            "Memphis": 0.92,
            "New York": 1.38,
            "San Francisco": 1.42,
            "Chicago": 1.18,
            "Miami": 1.10,
        },
        dealshield_tile_profile="educational_middle_school_v1",
        scope_items_profile="educational_middle_school_structural_v1",
        special_features={
            "gymnasium": 40,
            "cafeteria": 30,
            "science_labs": 35,
            "computer_lab": 25,
            "auditorium": 45,
            "athletic_field": 30,
        },
        base_revenue_per_sf_annual=0,
        base_revenue_per_student_annual=13000,
        students_per_sf=0.00625,
        occupancy_rate_base=0.95,
        occupancy_rate_premium=0.98,
        operating_margin_base=0.05,
        operating_margin_premium=0.08,
    ),
)
