SCOPE_ITEM_DEFAULTS = {}

SCOPE_ITEM_PROFILES = {
    "healthcare_medical_office_building_structural_v1": {
        "trade_profiles": [
            {
                "trade_key": "structural",
                "trade_label": "Structural",
                "items": [
                    {
                        "key": "foundations_slab_footings",
                        "label": "Foundations, slab, and footings",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "structural_frame",
                        "label": "Structural frame (steel/wood)",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "roof_structure_deck",
                        "label": "Roof structure and deck",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "exterior_envelope_structural_allowance",
                        "label": "Exterior envelope structural allowances",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.12},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "misc_stairs_supports",
                        "label": "Misc. structural, stairs, and supports",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.10},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
            {
                "trade_key": "mechanical",
                "trade_label": "Mechanical",
                "items": [
                    {
                        "key": "hvac_air_distribution",
                        "label": "HVAC air distribution and terminals",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.28},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "ventilation_exhaust_allowance",
                        "label": "Ventilation and exhaust allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "controls_bms_allowance",
                        "label": "Controls/BMS allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.12},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "hot_water_hydronic_allowance",
                        "label": "Hot water and hydronic allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "specialty_hvac_allowance",
                        "label": "Specialty HVAC allowance (clinical)",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "electrical",
                "trade_label": "Electrical",
                "items": [
                    {
                        "key": "main_service_distribution",
                        "label": "Main service and distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.25},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "lighting_receptacles",
                        "label": "Lighting and receptacles",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "low_voltage_data_allowance",
                        "label": "Low-voltage and data allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "emergency_power_allowance",
                        "label": "Emergency/backup power allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.15},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "controls_bms_integration",
                        "label": "Controls/BMS integration",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.12},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "plumbing",
                "trade_label": "Plumbing",
                "items": [
                    {
                        "key": "restroom_groups",
                        "label": "Restroom groups (fixtures, waste, vent)",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.35},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 15000.0, "minimum": 1},
                        },
                    },
                    {
                        "key": "domestic_water_sanitary",
                        "label": "Domestic water and sanitary piping",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "clinical_sinks_med_water_allowance",
                        "label": "Clinical sinks and med water allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.15},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "roof_drains_storm_tie_in",
                        "label": "Roof drains and storm tie-in allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
            {
                "trade_key": "finishes",
                "trade_label": "Finishes",
                "items": [
                    {
                        "key": "clinical_finishes_allowance",
                        "label": "Clinical-grade finishes allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "partitions_ceilings_allowance",
                        "label": "Partitions and ceilings allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "flooring_package_allowance",
                        "label": "Flooring package allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "millwork_casework_allowance",
                        "label": "Millwork and casework allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.14},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "lobby_common_finishes",
                        "label": "Lobby and common area finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
        ],
    },
    "healthcare_urgent_care_structural_v1": {
        "trade_profiles": [
            {
                "trade_key": "structural",
                "trade_label": "Structural",
                "items": [
                    {
                        "key": "concrete_slab_on_grade",
                        "label": "Concrete slab on grade (clinic baseline)",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.25},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "foundations_footings",
                        "label": "Foundations, footings, and thickened slabs",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "structural_framing",
                        "label": "Structural framing (steel or CMU bearing)",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.25},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "exterior_wall_envelope",
                        "label": "Exterior wall envelope and sheathing",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "roof_structure_system",
                        "label": "Roof structure and decking",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.10},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
            {
                "trade_key": "mechanical",
                "trade_label": "Mechanical",
                "items": [
                    {
                        "key": "hvac_ventilation_baseline",
                        "label": "HVAC/ventilation baseline",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.34},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "exhaust_clinical_allowance",
                        "label": "Exhaust allowance (bathroom/clinical)",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "air_distribution_balancing",
                        "label": "Air distribution and balancing",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "controls_bms_allowance",
                        "label": "Controls/BMS allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "electrical",
                "trade_label": "Electrical",
                "items": [
                    {
                        "key": "service_distribution",
                        "label": "Service and distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.28},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "lighting_power",
                        "label": "Lighting and power",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.34},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "low_voltage_systems_allowance",
                        "label": "Low-voltage systems allowance",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "emergency_power_allowance",
                        "label": "Emergency power allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "plumbing",
                "trade_label": "Plumbing",
                "items": [
                    {
                        "key": "restroom_groups",
                        "label": "Restroom groups (fixtures, waste, vent)",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.35},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 8000.0, "minimum": 1},
                        },
                    },
                    {
                        "key": "domestic_water_sanitary",
                        "label": "Domestic water and sanitary piping",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "clinical_sinks_allowance",
                        "label": "Clinical sinks allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "mop_service_sinks_allowance",
                        "label": "Mop and service sinks allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.15},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "finishes",
                "trade_label": "Finishes",
                "items": [
                    {
                        "key": "clinical_partitions_ceilings",
                        "label": "Clinical partitions and ceilings",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "flooring_package",
                        "label": "Flooring package",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.28},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "paint_wall_protection",
                        "label": "Paint and wall protection",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "millwork_casework_allowance",
                        "label": "Millwork and casework allowance",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
        ],
    },
}
