"""Scope item profiles for recreation subtypes."""


SCOPE_ITEM_DEFAULTS = {
    "default_profile_by_subtype": {
        "fitness_center": "recreation_fitness_center_structural_v1",
        "sports_complex": "recreation_sports_complex_structural_v1",
        "aquatic_center": "recreation_aquatic_center_structural_v1",
        "recreation_center": "recreation_recreation_center_structural_v1",
        "stadium": "recreation_stadium_structural_v1",
    },
}


SCOPE_ITEM_PROFILES = {
    "recreation_fitness_center_structural_v1": {
        "profile_id": "recreation_fitness_center_structural_v1",
        "trade_profiles": [
            {
                "trade_key": "structural",
                "trade_label": "Structural",
                "items": [
                    {
                        "key": "fitness_center_open_gym_framing",
                        "label": "Open Gym Framing",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_freeweight_zone_slab_reinforcement",
                        "label": "Freeweight Zone Slab Reinforcement",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_group_studio_partition_support",
                        "label": "Group Studio Partition Support",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_rooftop_mech_support_steel",
                        "label": "Rooftop Mechanical Support Steel",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "mechanical",
                "trade_label": "Mechanical",
                "items": [
                    {
                        "key": "fitness_center_high_air_change_supply",
                        "label": "High Air-Change Supply",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_group_studio_hvac_controls",
                        "label": "Group Studio HVAC Controls",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "fitness_center_recovery_ventilation",
                        "label": "Energy Recovery Ventilation",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "fitness_center_locker_makeup_air",
                        "label": "Locker Makeup Air",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "fitness_center_building_automation_sequences",
                        "label": "Building Automation Sequences",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "electrical",
                "trade_label": "Electrical",
                "items": [
                    {
                        "key": "fitness_center_power_distribution",
                        "label": "Power Distribution for Exercise Equipment",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.29},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "fitness_center_lighting_controls",
                        "label": "Layered Lighting and Controls",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.27},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_av_audio_system",
                        "label": "Group Studio AV/Audio",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "fitness_center_access_control",
                        "label": "Access Control and Security",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "plumbing",
                "trade_label": "Plumbing",
                "items": [
                    {
                        "key": "fitness_center_locker_showers",
                        "label": "Locker Showers and Fixtures",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.38},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 12000.0, "minimum": 1},
                        },
                    },
                    {
                        "key": "fitness_center_domestic_hot_water",
                        "label": "Domestic Hot Water and Recirculation",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.34},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "fitness_center_drinking_fountain_fills",
                        "label": "Drinking Fountain and Bottle Fill Stations",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.28},
                        "quantity_rule": {"type": "constant", "params": {"value": 4}},
                    },
                ],
            },
            {
                "trade_key": "finishes",
                "trade_label": "Finishes",
                "items": [
                    {
                        "key": "fitness_center_impact_flooring",
                        "label": "Impact-Resistant Fitness Flooring",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_acoustic_treatments",
                        "label": "Acoustic Wall/Ceiling Treatments",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_locker_room_finishes",
                        "label": "Locker Room Finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "fitness_center_reception_millwork",
                        "label": "Reception Millwork and Feature Elements",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
        ],
    },
    "recreation_sports_complex_structural_v1": {
        "profile_id": "recreation_sports_complex_structural_v1",
        "trade_profiles": [
            {
                "trade_key": "structural",
                "trade_label": "Structural",
                "items": [
                    {
                        "key": "sports_complex_long_span_roof_framing",
                        "label": "Long-Span Roof Framing",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "sports_complex_court_slab_system",
                        "label": "Court Slab and Levelness Control",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "sports_complex_bleacher_support_structure",
                        "label": "Bleacher Support Structure",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_scoreboard_support_steel",
                        "label": "Scoreboard Support Steel",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_expansion_joint_package",
                        "label": "Expansion Joint Package",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "mechanical",
                "trade_label": "Mechanical",
                "items": [
                    {
                        "key": "sports_complex_bowl_ventilation",
                        "label": "Large-Volume Ventilation",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.28},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "sports_complex_event_mode_controls",
                        "label": "Event-Mode Controls",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_locker_exhaust",
                        "label": "Locker Room Exhaust and Makeup Air",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_dehumidification_zones",
                        "label": "Localized Dehumidification Zones",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "electrical",
                "trade_label": "Electrical",
                "items": [
                    {
                        "key": "sports_complex_event_lighting",
                        "label": "Event Lighting Distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.29},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_scoreboard_feeds",
                        "label": "Scoreboard and AV Feeds",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.27},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_emergency_power",
                        "label": "Emergency Power and Egress Lighting",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_access_control_it",
                        "label": "Access Control and Event IT",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "plumbing",
                "trade_label": "Plumbing",
                "items": [
                    {
                        "key": "sports_complex_team_locker_plumbing",
                        "label": "Team Locker Room Plumbing",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.40},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 15000.0, "minimum": 2},
                        },
                    },
                    {
                        "key": "sports_complex_spectator_restroom_groups",
                        "label": "Spectator Restroom Groups",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.35},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 18000.0, "minimum": 2},
                        },
                    },
                    {
                        "key": "sports_complex_concession_domestic_water",
                        "label": "Concession and Domestic Water Distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.25},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "finishes",
                "trade_label": "Finishes",
                "items": [
                    {
                        "key": "sports_complex_sport_floor_systems",
                        "label": "Sport Floor Systems",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "sports_complex_bleacher_and_guardrail_finishes",
                        "label": "Bleacher/Guardrail Finishes",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "sports_complex_locker_room_finish_package",
                        "label": "Locker Room Finish Package",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "sports_complex_concourse_durable_finishes",
                        "label": "Concourse Durable Finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
        ],
    },
    "recreation_aquatic_center_structural_v1": {
        "profile_id": "recreation_aquatic_center_structural_v1",
        "trade_profiles": [
            {
                "trade_key": "structural",
                "trade_label": "Structural",
                "items": [
                    {
                        "key": "aquatic_center_pool_shell_structure",
                        "label": "Pool Shell Structure",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.28},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "aquatic_center_natatorium_long_span_roof",
                        "label": "Natatorium Long-Span Roof",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "aquatic_center_spectator_support_framing",
                        "label": "Spectator Support Framing",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "aquatic_center_equipment_room_slab_and_pads",
                        "label": "Equipment Room Slab and Pads",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "mechanical",
                "trade_label": "Mechanical",
                "items": [
                    {
                        "key": "aquatic_center_natatorium_dehumidification_units",
                        "label": "Natatorium Dehumidification Units",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_pool_air_distribution",
                        "label": "Pool Air Distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.17},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_outside_air_energy_recovery",
                        "label": "Outside-Air Energy Recovery",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.17},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_spectator_hvac_distribution",
                        "label": "Spectator HVAC Distribution",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "aquatic_center_chemical_room_exhaust",
                        "label": "Chemical Room Exhaust",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_controls_and_monitoring",
                        "label": "Humidity Controls and Monitoring",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "electrical",
                "trade_label": "Electrical",
                "items": [
                    {
                        "key": "aquatic_center_corrosion_resistant_distribution",
                        "label": "Corrosion-Resistant Distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_underwater_lighting",
                        "label": "Underwater Lighting Systems",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.21},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_life_safety_power",
                        "label": "Life-Safety Power and Egress",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_mechanical_equipment_feeds",
                        "label": "Mechanical Equipment Feeds",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.19},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_timing_scoreboard_and_av",
                        "label": "Timing, Scoreboard, and AV",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "plumbing",
                "trade_label": "Plumbing",
                "items": [
                    {
                        "key": "aquatic_center_pool_circulation_piping",
                        "label": "Pool Circulation Piping",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_filtration_and_backwash",
                        "label": "Filtration and Backwash Systems",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.21},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_chemical_feed_and_storage",
                        "label": "Chemical Feed and Storage",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "aquatic_center_locker_restroom_groups",
                        "label": "Locker/Restroom Fixture Groups",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.19},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 12000.0, "minimum": 2},
                        },
                    },
                    {
                        "key": "aquatic_center_pool_deck_drainage",
                        "label": "Pool Deck Drainage and Trench Systems",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "finishes",
                "trade_label": "Finishes",
                "items": [
                    {
                        "key": "aquatic_center_pool_deck_finish",
                        "label": "Pool Deck and Non-Slip Finish",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.29},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "aquatic_center_natatorium_wall_finishes",
                        "label": "Natatorium Wall/Ceiling Finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "aquatic_center_locker_room_finish_package",
                        "label": "Locker Room Finish Package",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "aquatic_center_spectator_area_finishes",
                        "label": "Spectator Area Finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.21},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
        ],
    },
    "recreation_recreation_center_structural_v1": {
        "profile_id": "recreation_recreation_center_structural_v1",
        "trade_profiles": [
            {
                "trade_key": "structural",
                "trade_label": "Structural",
                "items": [
                    {
                        "key": "recreation_center_multipurpose_hall_framing",
                        "label": "Multipurpose Hall Framing",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.29},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "recreation_center_gym_slab_reinforcement",
                        "label": "Gym Slab Reinforcement",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.27},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "recreation_center_activity_wing_structure",
                        "label": "Activity Wing Structure",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "recreation_center_rooftop_support_and_screening",
                        "label": "Rooftop Support and Screening",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "mechanical",
                "trade_label": "Mechanical",
                "items": [
                    {
                        "key": "recreation_center_shared_zone_air_distribution",
                        "label": "Shared-Zone Air Distribution",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "recreation_center_program_mode_controls",
                        "label": "Program-Mode Controls",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "recreation_center_gym_ventilation",
                        "label": "Gym and Studio Ventilation",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "recreation_center_locker_makeup_air",
                        "label": "Locker Makeup Air",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "recreation_center_energy_recovery_system",
                        "label": "Energy Recovery System",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "electrical",
                "trade_label": "Electrical",
                "items": [
                    {
                        "key": "recreation_center_general_power_distribution",
                        "label": "General Power Distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.29},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "recreation_center_lighting_and_daylight_controls",
                        "label": "Lighting and Daylight Controls",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.27},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "recreation_center_av_and_wifi_backbone",
                        "label": "AV and Wi-Fi Backbone",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "recreation_center_access_and_security",
                        "label": "Access/Security Systems",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "plumbing",
                "trade_label": "Plumbing",
                "items": [
                    {
                        "key": "recreation_center_restroom_fixture_groups",
                        "label": "Restroom Fixture Groups",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.38},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 14000.0, "minimum": 1},
                        },
                    },
                    {
                        "key": "recreation_center_locker_room_plumbing",
                        "label": "Locker Room Plumbing",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.34},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "recreation_center_domestic_hot_water_loop",
                        "label": "Domestic Hot Water Loop",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.28},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "finishes",
                "trade_label": "Finishes",
                "items": [
                    {
                        "key": "recreation_center_multipurpose_room_finishes",
                        "label": "Multipurpose Room Finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "recreation_center_gym_floor_and_wall_package",
                        "label": "Gym Floor and Wall Package",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "recreation_center_lobby_and_reception_millwork",
                        "label": "Lobby/Reception Millwork",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "recreation_center_activity_room_durable_surfaces",
                        "label": "Activity Room Durable Surfaces",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
        ],
    },
    "recreation_stadium_structural_v1": {
        "profile_id": "recreation_stadium_structural_v1",
        "trade_profiles": [
            {
                "trade_key": "structural",
                "trade_label": "Structural",
                "items": [
                    {
                        "key": "stadium_seating_bowl_superstructure",
                        "label": "Seating Bowl Superstructure",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_concourse_long_span_systems",
                        "label": "Concourse Long-Span Systems",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_vertical_core_hardening",
                        "label": "Vertical Core Hardening",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.17},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_roof_cantilever_structure",
                        "label": "Roof Cantilever Structure",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.16},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_video_board_support_steel",
                        "label": "Video Board Support Steel",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.15},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_expansion_joint_and_movement_systems",
                        "label": "Expansion Joint and Movement Systems",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.14},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "mechanical",
                "trade_label": "Mechanical",
                "items": [
                    {
                        "key": "stadium_crowd_mode_air_supply",
                        "label": "Crowd-Mode Air Supply",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_concourse_ventilation_distribution",
                        "label": "Concourse Ventilation Distribution",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.21},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_premium_suite_hvac",
                        "label": "Premium Suite HVAC",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_kitchen_exhaust_makeup_air",
                        "label": "Concession Kitchen Exhaust and Makeup Air",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.19},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_controls_and_smoke_purge_sequences",
                        "label": "Controls and Smoke/Purge Sequences",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "electrical",
                "trade_label": "Electrical",
                "items": [
                    {
                        "key": "stadium_event_lighting_distribution",
                        "label": "Event Lighting Distribution",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_broadcast_and_production_power",
                        "label": "Broadcast and Production Power",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.21},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_scoreboard_and_display_feeds",
                        "label": "Scoreboard and Display Feeds",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_emergency_power_and_egress",
                        "label": "Emergency Power and Egress",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.19},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_turnstile_access_and_network",
                        "label": "Turnstile Access and Network",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "plumbing",
                "trade_label": "Plumbing",
                "items": [
                    {
                        "key": "stadium_spectator_restroom_banks",
                        "label": "Spectator Restroom Banks",
                        "unit": "EA",
                        "allocation": {"type": "share_of_trade", "share": 0.30},
                        "quantity_rule": {
                            "type": "restroom_groups",
                            "params": {"sf_per_group": 16000.0, "minimum": 4},
                        },
                    },
                    {
                        "key": "stadium_team_locker_room_plumbing",
                        "label": "Team Locker Room Plumbing",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.26},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_concession_domestic_and_sanitary",
                        "label": "Concession Domestic and Sanitary",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.24},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_field_or_event_water_services",
                        "label": "Field/Event Water Services",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                ],
            },
            {
                "trade_key": "finishes",
                "trade_label": "Finishes",
                "items": [
                    {
                        "key": "stadium_concourse_durable_finish_systems",
                        "label": "Concourse Durable Finish Systems",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.22},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_seating_and_guardrail_finishes",
                        "label": "Seating and Guardrail Finishes",
                        "unit": "LS",
                        "allocation": {"type": "share_of_trade", "share": 0.21},
                        "quantity_rule": {"type": "constant", "params": {"value": 1}},
                    },
                    {
                        "key": "stadium_premium_suite_finish_package",
                        "label": "Premium Suite Finish Package",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.20},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_team_and_official_area_finishes",
                        "label": "Team and Official Area Finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.19},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                    {
                        "key": "stadium_back_of_house_service_finishes",
                        "label": "Back-of-House Service Finishes",
                        "unit": "SF",
                        "allocation": {"type": "share_of_trade", "share": 0.18},
                        "quantity_rule": {"type": "sf", "params": {}},
                    },
                ],
            },
        ],
    },
}
