from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.RETAIL,
    "big_box",
    BuildingConfig(
        display_name="Big Box Retail",
        base_cost_per_sf=125,
        cost_range=(100, 150),
        equipment_cost_per_sf=3,
        typical_floors=1,
        trades=TradeBreakdown(
            structural=0.35,
            mechanical=0.18,
            electrical=0.14,
            plumbing=0.08,
            finishes=0.25,
        ),
        soft_costs=SoftCosts(
            design_fees=0.04,
            permits=0.02,
            legal=0.012,
            financing=0.025,
            contingency=0.06,
            testing=0.005,
            construction_management=0.02,
            startup=0.008,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.72,
                debt_rate=0.06,
                equity_ratio=0.28,
                target_dscr=1.20,
                target_roi=0.09,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "big box",
                "anchor tenant",
                "department store",
                "superstore",
                "warehouse retail",
            ],
            priority=11,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.90,
            "Memphis": 0.88,
            "New York": 1.30,
            "San Francisco": 1.35,
        },
        special_features={
            "loading_dock": {
                "basis": "COUNT_BASED",
                "value": 65000,
                "count_pricing_mode": "overage_above_default",
                "count_override_keys": [
                    "extra_loading_dock_count",
                    "extra_dock_count",
                    "loading_dock_count",
                    "dock_door_count",
                    "dock_count",
                ],
                "default_count_bands": [
                    {"label": "small_box", "max_square_footage": 100000, "count": 4},
                    {"label": "mid_box", "max_square_footage": 200000, "count": 6},
                    {"label": "large_box", "max_square_footage": 300000, "count": 8},
                    {"label": "anchor_box", "count": 10},
                ],
                "unit_label": "dock",
            },
            "mezzanine": {
                "basis": "AREA_SHARE_GSF",
                "value": 25,
                "area_share_of_gsf": 0.05,
            },
            "auto_center": {
                "basis": "AREA_SHARE_GSF",
                "value": 45,
                "area_share_of_gsf": 0.08,
            },
            "garden_center": {
                "basis": "AREA_SHARE_GSF",
                "value": 30,
                "area_share_of_gsf": 0.10,
            },
            "warehouse_racking": {
                "basis": "AREA_SHARE_GSF",
                "value": 15,
                "area_share_of_gsf": 0.18,
            },
            "refrigerated_storage": {
                "basis": "AREA_SHARE_GSF",
                "value": 35,
                "area_share_of_gsf": 0.06,
            },
            "curbside_pickup": {
                "basis": "COUNT_BASED",
                "value": 8000,
                "count": 4,
                "count_override_keys": [
                    "curbside_pickup_stall_count",
                    "pickup_stall_count",
                    "curbside_stall_count",
                    "pickup_count",
                ],
                "unit_label": "stall",
            },
        },
        special_feature_pricing_statuses={
            "loading_dock": "included_in_baseline",
            "mezzanine": "included_in_baseline",
            "auto_center": "included_in_baseline",
            "garden_center": "included_in_baseline",
            "warehouse_racking": "incremental",
            "refrigerated_storage": "included_in_baseline",
            "curbside_pickup": "incremental",
        },
        dealshield_tile_profile="retail_big_box_v1",
        scope_items_profile="retail_big_box_structural_v1",
        base_revenue_per_sf_annual=25,
        base_sales_per_sf_annual=200,
        occupancy_rate_base=0.95,
        occupancy_rate_premium=0.98,
        operating_margin_base=0.60,
        operating_margin_premium=0.65,
    ),
)
