from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.RETAIL,
    "shopping_center",
    BuildingConfig(
        display_name="Shopping Center",
        base_cost_per_sf=150,
        cost_range=(125, 175),
        equipment_cost_per_sf=5,
        typical_floors=1,
        trades=TradeBreakdown(
            structural=0.30,
            mechanical=0.20,
            electrical=0.15,
            plumbing=0.10,
            finishes=0.25,
        ),
        soft_costs=SoftCosts(
            design_fees=0.05,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.07,
            testing=0.005,
            construction_management=0.025,
            startup=0.01,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.058,
                equity_ratio=0.30,
                target_dscr=1.25,
                target_roi=0.10,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "shopping center",
                "retail center",
                "strip mall",
                "strip center",
                "plaza",
                "shopping plaza",
            ],
            priority=10,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.92,
            "Memphis": 0.90,
            "New York": 1.35,
            "San Francisco": 1.40,
        },
        special_features={
            "covered_walkway": {
                "basis": "AREA_SHARE_GSF",
                "value": 20,
                "area_share_of_gsf": 0.08,
            },
            "loading_dock": {
                "basis": "COUNT_BASED",
                "value": 65000,
                "count_pricing_mode": "overage_above_default",
                "count_override_keys": [
                    "extra_loading_dock_count",
                    "extra_dock_count",
                    "loading_dock_count",
                    "dock_door_count",
                    "dock_count",
                ],
                "default_count_bands": [
                    {"label": "neighborhood_center", "max_square_footage": 75000, "count": 1},
                    {"label": "community_center", "max_square_footage": 175000, "count": 2},
                    {"label": "regional_center", "count": 4},
                ],
                "unit_label": "dock",
            },
            "monument_signage": {
                "basis": "COUNT_BASED",
                "value": 15000,
                "count": 1,
                "count_pricing_mode": "overage_above_default",
                "count_override_keys": ["monument_sign_count", "sign_count"],
                "unit_label": "sign",
            },
            "outdoor_seating": {
                "basis": "AREA_SHARE_GSF",
                "value": 20,
                "area_share_of_gsf": 0.03,
            },
            "drive_thru": {
                "basis": "COUNT_BASED",
                "value": 85000,
                "count": 1,
                "count_override_keys": ["drive_thru_lane_count", "drive_thru_count", "lane_count"],
                "unit_label": "lane",
            },
            "storage_units": {
                "basis": "AREA_SHARE_GSF",
                "value": 15,
                "area_share_of_gsf": 0.05,
            },
        },
        special_feature_pricing_statuses={
            "covered_walkway": "included_in_baseline",
            "loading_dock": "included_in_baseline",
            "monument_signage": "included_in_baseline",
            "outdoor_seating": "incremental",
            "drive_thru": "incremental",
            "storage_units": "incremental",
        },
        dealshield_tile_profile="retail_shopping_center_v1",
        scope_items_profile="retail_shopping_center_structural_v1",
        base_revenue_per_sf_annual=35,
        base_sales_per_sf_annual=350,
        occupancy_rate_base=0.92,
        occupancy_rate_premium=0.95,
        operating_margin_base=0.65,
        operating_margin_premium=0.70,
    ),
)
