"""Add team and sharing models

Revision ID: 8326beeb3bf6
Revises: add_scenario_name
Create Date: 2025-07-29 17:18:45.450945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8326beeb3bf6'
down_revision = 'add_scenario_name'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###