from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "imaging_center",
    BuildingConfig(
        display_name="Diagnostic Imaging Center",
        base_cost_per_sf=420,
        cost_range=(420, 560),
        facility_metrics_profile="healthcare_outpatient",
        scope_items_profile="healthcare_imaging_center_structural_v1",
        dealshield_tile_profile="healthcare_imaging_center_v1",
        equipment_cost_per_sf=120,
        typical_floors=1,
        ti_allowance_per_sf=0,
        trades=TradeBreakdown(
            structural=0.24,
            mechanical=0.32,
            electrical=0.24,
            plumbing=0.08,
            finishes=0.12,
        ),
        soft_costs=SoftCosts(
            design_fees=0.09,
            permits=0.02,
            legal=0.02,
            financing=0.03,
            contingency=0.07,
            testing=0.02,
            construction_management=0.04,
            startup=0.02,
        ),
        soft_costs_pct_of_hard=0.25,
        contingency_pct_of_hard=0.07,
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.065,
                equity_ratio=0.35,
                target_dscr=1.4,
                target_roi=0.10,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "imaging center",
                "diagnostic center",
                "MRI",
                "CT scan",
                "radiology",
                "x-ray",
                "medical imaging",
                "diagnostic imaging",
            ],
            priority=3,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.96,
            "Memphis": 0.94,
            "New York": 1.30,
            "San Francisco": 1.35,
            "Chicago": 1.15,
            "Miami": 1.08,
        },
        special_features={
            "mri_suite": 80,
            "ct_suite": 60,
            "pet_scan": 90,
            "mammography": 35,
            "ultrasound": 20,
            "hc_imaging_second_mri": 100,
            "hc_imaging_pet_ct_suite": 150,
            "hc_imaging_interventional_rad": 125,
        },
        base_revenue_per_sf_annual=525,
        operating_margin_base=0.22,
        occupancy_rate_base=0.80,
        occupancy_rate_premium=0.88,
        units_per_sf=1.0 / 800.0,
        financial_metrics={
            "primary_unit": "scan rooms",
            "units_per_sf": 1.0 / 800.0,
            "revenue_per_unit_annual": 850000,
        },
        yield_on_cost_hurdle=0.10,
        dscr_target=1.4,
        basis_risk_tolerance_pct=0.10,
        labor_cost_ratio=0.35,
        supply_cost_ratio=0.08,
        management_fee_ratio=0.10,
        insurance_cost_ratio=0.02,
        utility_cost_ratio=0.04,
        maintenance_cost_ratio=0.15,
        equipment_lease_ratio=0.10,
    ),
)
