from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "medical_office_building",
    BuildingConfig(
        display_name="Medical Office Building",
        base_cost_per_sf=270,
        cost_range=(260, 320),
        facility_metrics_profile="healthcare_outpatient",
        equipment_cost_per_sf=0,
        typical_floors=3,
        ti_allowance_per_sf=40,
        trades=TradeBreakdown(
            structural=0.22,
            mechanical=0.28,
            electrical=0.16,
            plumbing=0.12,
            finishes=0.22,
        ),
        soft_costs=SoftCosts(
            design_fees=0.06,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.008,
            construction_management=0.03,
            startup=0.01,
        ),
        soft_costs_pct_of_hard=0.20,
        contingency_pct_of_hard=0.05,
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.065,
                equity_ratio=0.30,
                target_dscr=1.35,
                target_roi=0.07,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "medical office building",
                "mob",
                "medical office suites",
                "physician office",
                "doctor office building",
                "medical office landlord",
                "medical office tower",
                "medical office complex",
            ],
            priority=4,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.96,
            "Memphis": 0.94,
            "New York": 1.28,
            "San Francisco": 1.34,
            "Chicago": 1.15,
            "Miami": 1.08,
        },
        special_features={
            "tenant_improvements": 40,
            "ambulatory_buildout": 60,
            "ambulatory_imaging": 35,
            "mob_imaging_ready_shell": 40,
            "mob_enhanced_mep": 20,
            "mob_procedure_suite": 30,
            "mob_pharmacy_shell": 15,
            "mob_covered_dropoff": 15,
        },
        financial_metrics={
            "primary_unit": "tenant suites",
            "units_per_sf": 1.0 / 2500.0,
            "revenue_per_unit_annual": 100000,
            "display_name": "Per Suite Performance",
        },
        base_revenue_per_sf_annual=40,
        operating_margin_base=0.65,
        operating_margin_premium=0.70,
        yield_on_cost_hurdle=0.07,
        dscr_target=1.35,
        basis_risk_tolerance_pct=0.08,
    ),
)
