from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    ProjectClass,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "medical_center",
    BuildingConfig(
        display_name="Medical Center",
        base_cost_per_sf=750,
        cost_range=(850, 1000),
        equipment_cost_per_sf=150,
        typical_floors=4,
        trades=TradeBreakdown(
            structural=0.18,
            mechanical=0.34,
            electrical=0.20,
            plumbing=0.15,
            finishes=0.13,
        ),
        soft_costs=SoftCosts(
            design_fees=0.075,
            permits=0.025,
            legal=0.02,
            financing=0.03,
            contingency=0.10,
            testing=0.015,
            construction_management=0.04,
            startup=0.02,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.068,
                equity_ratio=0.35,
                target_dscr=1.25,
                target_roi=0.09,
            ),
            OwnershipType.NON_PROFIT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.042,
                equity_ratio=0.15,
                philanthropy_ratio=0.10,
                target_dscr=1.18,
                target_roi=0.04,
            ),
        },
        nlp=NLPConfig(
            keywords=[
                "medical center",
                "health center",
                "healthcare center",
                "comprehensive care",
                "medical complex",
            ],
            priority=2,
            incompatible_classes=[ProjectClass.TENANT_IMPROVEMENT],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.96,
            "Memphis": 0.94,
            "New York": 1.33,
            "San Francisco": 1.38,
            "Chicago": 1.18,
            "Miami": 1.10,
        },
        special_features={
            "emergency": 45,
            "surgery": 60,
            "imaging": 35,
            "laboratory": 25,
            "specialty_clinic": 30,
        },
        base_revenue_per_sf_annual=55,
        occupancy_rate_base=0.88,
        occupancy_rate_premium=0.92,
        operating_margin_base=0.25,
        operating_margin_premium=0.30,
        labor_cost_ratio=0.48,
        supply_cost_ratio=0.16,
        management_fee_ratio=0.11,
        insurance_cost_ratio=0.03,
        utility_cost_ratio=0.03,
        maintenance_cost_ratio=0.04,
    ),
)
