from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    ProjectClass,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "medical_center",
    BuildingConfig(
        display_name="Medical Center",
        base_cost_per_sf=750,
        cost_range=(850, 1000),
        scope_items_profile="healthcare_medical_center_structural_v1",
        dealshield_tile_profile="healthcare_medical_center_v1",
        equipment_cost_per_sf=150,
        typical_floors=4,
        trades=TradeBreakdown(
            structural=0.18,
            mechanical=0.34,
            electrical=0.20,
            plumbing=0.15,
            finishes=0.13,
        ),
        soft_costs=SoftCosts(
            design_fees=0.075,
            permits=0.025,
            legal=0.02,
            financing=0.03,
            contingency=0.10,
            testing=0.015,
            construction_management=0.04,
            startup=0.02,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.068,
                equity_ratio=0.35,
                target_dscr=1.25,
                target_roi=0.09,
            ),
            OwnershipType.NON_PROFIT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.042,
                equity_ratio=0.15,
                philanthropy_ratio=0.10,
                target_dscr=1.18,
                target_roi=0.04,
            ),
        },
        nlp=NLPConfig(
            keywords=[
                "medical center",
                "health center",
                "healthcare center",
                "comprehensive care",
                "medical complex",
            ],
            priority=2,
            incompatible_classes=[ProjectClass.TENANT_IMPROVEMENT],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.96,
            "Memphis": 0.94,
            "New York": 1.33,
            "San Francisco": 1.38,
            "Chicago": 1.18,
            "Miami": 1.10,
        },
        special_features={
            "emergency": 45,
            "surgery": 60,
            "imaging": 35,
            "laboratory": 25,
            "specialty_clinic": 30,
        },
        financial_metrics={
            "primary_unit": "beds",
            "units_per_sf": 0.00070,
            "revenue_per_unit_annual": 390000,
            "target_occupancy": 0.84,
            "breakeven_occupancy": 0.72,
            "market_rate_type": "daily_rate",
            "market_rate_default": 1350,
            "display_name": "Per Bed Performance",
            "operational_metrics": {
                "throughput_per_unit_day": 0.92,
                "operating_days_per_year": 365,
                "utilization_target": 0.84,
                "average_length_of_stay_days": 3.9,
                "clinical_staff_fte_per_unit": 1.45,
                "support_staff_fte_per_unit": 0.85,
                "throughput_label": "Average Daily Census",
                "utilization_label": "Service-Line Bed Occupancy",
                "staffing_intensity_label": "FTE per Licensed Bed",
                "efficiency_label": "Clinical Throughput Efficiency",
                "efficiency_green_threshold": 83.0,
                "efficiency_yellow_threshold": 69.0,
            },
        },
        base_revenue_per_sf_annual=55,
        occupancy_rate_base=0.88,
        occupancy_rate_premium=0.92,
        operating_margin_base=0.25,
        operating_margin_premium=0.30,
        labor_cost_ratio=0.48,
        supply_cost_ratio=0.16,
        management_fee_ratio=0.11,
        insurance_cost_ratio=0.03,
        utility_cost_ratio=0.03,
        maintenance_cost_ratio=0.04,
    ),
)
