from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "nursing_home",
    BuildingConfig(
        display_name="Senior Care Facility",
        base_cost_per_sf=275,
        cost_range=(275, 325),
        equipment_cost_per_sf=10,
        typical_floors=2,
        trades=TradeBreakdown(
            structural=0.26,
            mechanical=0.23,
            electrical=0.11,
            plumbing=0.15,
            finishes=0.25,
        ),
        soft_costs=SoftCosts(
            design_fees=0.06,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.008,
            construction_management=0.03,
            startup=0.015,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.066,
                equity_ratio=0.30,
                target_dscr=1.20,
                target_roi=0.09,
            ),
            OwnershipType.NON_PROFIT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.043,
                equity_ratio=0.15,
                grants_ratio=0.10,
                target_dscr=1.15,
                target_roi=0.02,
            ),
        },
        nlp=NLPConfig(
            keywords=[
                "nursing home",
                "senior care",
                "assisted living",
                "elder care",
                "senior living",
                "long term care",
                "skilled nursing",
            ],
            priority=8,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.94,
            "Memphis": 0.92,
            "New York": 1.25,
            "San Francisco": 1.30,
            "Chicago": 1.10,
            "Miami": 1.08,
        },
        special_features={
            "memory_care": 30,
            "therapy_room": 20,
            "dining_hall": 15,
            "activity_room": 12,
        },
        base_revenue_per_sf_annual=300,
        base_revenue_per_bed_annual=95000,
        beds_per_sf=0.0015,
        occupancy_rate_base=0.88,
        occupancy_rate_premium=0.92,
        operating_margin_base=0.12,
        operating_margin_premium=0.18,
        labor_cost_ratio=0.60,
        supply_cost_ratio=0.10,
        food_cost_ratio=0.08,
        management_fee_ratio=0.08,
        insurance_cost_ratio=0.02,
        utility_cost_ratio=0.04,
        maintenance_cost_ratio=0.03,
    ),
)
