from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "outpatient_clinic",
    BuildingConfig(
        display_name="Outpatient Clinic",
        base_cost_per_sf=380,
        cost_range=(400, 480),
        facility_metrics_profile="healthcare_outpatient",
        scope_items_profile="healthcare_outpatient_clinic_structural_v1",
        dealshield_tile_profile="healthcare_outpatient_clinic_v1",
        equipment_cost_per_sf=50,
        typical_floors=1,
        trades=TradeBreakdown(
            structural=0.25,
            mechanical=0.26,  # Enhanced ventilation
            electrical=0.12,
            plumbing=0.15,
            finishes=0.22,
        ),
        soft_costs=SoftCosts(
            design_fees=0.06,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.01,
            construction_management=0.03,
            startup=0.015,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.065,
                equity_ratio=0.30,
                target_dscr=1.20,
                target_roi=0.10,
            ),
            OwnershipType.NON_PROFIT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.045,
                equity_ratio=0.20,
                grants_ratio=0.05,
                target_dscr=1.15,
                target_roi=0.03,
            ),
        },
        nlp=NLPConfig(
            keywords=[
                "outpatient clinic",
                "primary care clinic",
                "primary care",
                "family medicine clinic",
                "family practice clinic",
                "internal medicine clinic",
                "health clinic",
                "ambulatory care",
                "outpatient facility",
                "exam rooms",
                "exam room",
            ],
            priority=3,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.95,
            "Memphis": 0.93,
            "New York": 1.28,
            "San Francisco": 1.32,
            "Chicago": 1.12,
            "Miami": 1.05,
        },
        special_features={
            "exam_rooms": 15,
            "procedure_room": 25,
            "laboratory": 20,
            "pharmacy": 30,
            "hc_outpatient_on_site_lab": 30,
            "hc_outpatient_imaging_pod": 60,
            "hc_outpatient_behavioral_suite": 25,
        },
        financial_metrics={
            "primary_unit": "exam rooms",
            "units_per_sf": 1 / 650,
            "revenue_per_unit_annual": 130000,
            "target_occupancy": 0.85,
            "breakeven_occupancy": 0.70,
            "market_rate_type": "revenue_per_visit",
            "market_rate_default": 120,
            "display_name": "Per Exam Room Performance",
            "operational_metrics": {
                "throughput_per_unit_day": 9.0,
                "operating_days_per_year": 260,
                "utilization_target": 0.78,
                "provider_fte_per_unit": 0.30,
                "support_fte_per_provider": 1.4,
                "specialist_fte_per_unit": 0.05,
                "specialist_label": "Care Coordination FTE",
                "throughput_label": "Visits / Day",
                "utilization_label": "Exam Room Utilization",
                "efficiency_label": "Visit Throughput Efficiency",
                "efficiency_green_threshold": 84.0,
                "efficiency_yellow_threshold": 69.0,
            },
        },
        base_revenue_per_sf_annual=195,
        base_revenue_per_visit=120,
        visits_per_day=50,
        days_per_year=260,
        occupancy_rate_base=0.85,
        occupancy_rate_premium=0.90,
        operating_margin_base=0.16,
        operating_margin_premium=0.20,
        labor_cost_ratio=0.42,
        supply_cost_ratio=0.10,
        management_fee_ratio=0.08,
        insurance_cost_ratio=0.02,
        utility_cost_ratio=0.02,
        maintenance_cost_ratio=0.03,
    ),
)
