from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "rehabilitation",
    BuildingConfig(
        display_name="Rehabilitation Center",
        base_cost_per_sf=325,
        cost_range=(400, 475),
        equipment_cost_per_sf=100,  # Therapy equipment
        typical_floors=2,
        trades=TradeBreakdown(
            structural=0.24,
            mechanical=0.25,
            electrical=0.13,
            plumbing=0.16,
            finishes=0.22,
        ),
        soft_costs=SoftCosts(
            design_fees=0.07,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.01,
            construction_management=0.035,
            startup=0.018,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.068,
                equity_ratio=0.35,
                target_dscr=1.23,
                target_roi=0.10,
            ),
            OwnershipType.NON_PROFIT: FinancingTerms(
                debt_ratio=0.75,
                debt_rate=0.045,
                equity_ratio=0.15,
                grants_ratio=0.10,
                target_dscr=1.15,
                target_roi=0.03,
            ),
        },
        nlp=NLPConfig(
            keywords=[
                "rehabilitation",
                "rehab center",
                "physical therapy",
                "occupational therapy",
                "speech therapy",
                "therapy center",
            ],
            priority=7,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.95,
            "Memphis": 0.93,
            "New York": 1.28,
            "San Francisco": 1.33,
            "Chicago": 1.12,
            "Miami": 1.06,
        },
        special_features={
            "therapy_gym": 40,
            "hydrotherapy": 50,
            "treatment_rooms": 20,
            "assessment_suite": 25,
        },
        base_revenue_per_sf_annual=350,
        base_revenue_per_bed_annual=280000,
        beds_per_sf=0.001,
        occupancy_rate_base=0.82,
        occupancy_rate_premium=0.88,
        operating_margin_base=0.18,
        operating_margin_premium=0.25,
        labor_cost_ratio=0.55,
        supply_cost_ratio=0.08,
        management_fee_ratio=0.10,
        insurance_cost_ratio=0.02,
        utility_cost_ratio=0.03,
        maintenance_cost_ratio=0.05,
    ),
)
