from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
    ProjectClass,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "surgical_center",
    BuildingConfig(
        display_name="Ambulatory Surgical Center",
        base_cost_per_sf=480,
        cost_range=(600, 780),
        facility_metrics_profile="healthcare_outpatient",
        scope_items_profile="healthcare_surgical_center_structural_v1",
        dealshield_tile_profile="healthcare_surgical_center_v1",
        equipment_cost_per_sf=180,
        typical_floors=1,
        ti_allowance_per_sf=0,
        trades=TradeBreakdown(
            structural=0.12,
            mechanical=0.40,  # Heavy MEP scope for OR pressurization
            electrical=0.20,
            plumbing=0.14,
            finishes=0.14,
        ),
        soft_costs=SoftCosts(
            design_fees=0.07,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.015,
            construction_management=0.025,
            startup=0.01,
        ),
        soft_costs_pct_of_hard=0.26,
        contingency_pct_of_hard=0.08,
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.65,
                debt_rate=0.065,
                equity_ratio=0.35,
                target_dscr=1.45,
                target_roi=0.115,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "surgical center",
                "ambulatory surgery",
                "ASC",
                "surgery center",
                "outpatient surgery",
                "day surgery",
                "same day surgery",
            ],
            priority=2,
            incompatible_classes=[ProjectClass.TENANT_IMPROVEMENT],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.96,
            "Memphis": 0.94,
            "New York": 1.32,
            "San Francisco": 1.38,
            "Chicago": 1.18,
            "Miami": 1.12,
        },
        special_features={
            "operating_room": 100,  # Per OR
            "recovery_room": 40,
            "pre_op": 35,
            "sterile_processing": 60,
            "hc_asc_expanded_pacu": 75,
            "hc_asc_sterile_core_upgrade": 50,
            "hc_asc_pain_management_suite": 60,
            "hc_asc_hybrid_or_cath_lab": 125,
        },
        financial_metrics={
            "primary_unit": "operating rooms",
            "units_per_sf": 1.0 / 950.0,
            "revenue_per_unit_annual": 1200000,
            "display_name": "Per OR Requirements",
        },
        base_revenue_per_sf_annual=650,
        operating_margin_base=0.24,
        yield_on_cost_hurdle=0.115,
        dscr_target=1.45,
        basis_risk_tolerance_pct=0.10,
        labor_cost_ratio=0.38,
        supply_cost_ratio=0.20,
        management_fee_ratio=0.07,
        insurance_cost_ratio=0.04,
        utility_cost_ratio=0.025,
        maintenance_cost_ratio=0.045,
    ),
)
