from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "urgent_care",
    BuildingConfig(
        display_name="Urgent Care Center",
        base_cost_per_sf=350,
        cost_range=(400, 475),
        facility_metrics_profile="healthcare_outpatient",
        scope_items_profile="healthcare_urgent_care_structural_v1",
        dealshield_tile_profile="healthcare_urgent_care_v1",
        equipment_cost_per_sf=75,
        typical_floors=1,
        trades=TradeBreakdown(
            structural=0.26,
            mechanical=0.25,
            electrical=0.13,
            plumbing=0.14,
            finishes=0.22,
        ),
        soft_costs=SoftCosts(
            design_fees=0.06,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.01,
            construction_management=0.03,
            startup=0.015,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.065,
                equity_ratio=0.30,
                target_dscr=1.20,
                target_roi=0.11,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "urgent care",
                "walk-in clinic",
                "immediate care",
                "express care",
                "quick care",
                "walk in",
            ],
            priority=3,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.95,
            "Memphis": 0.93,
            "New York": 1.25,
            "San Francisco": 1.30,
            "Chicago": 1.10,
            "Miami": 1.05,
        },
        special_features={
            "exam_rooms": {
                "basis": "COUNT_BASED",
                "value": 12000,
                "count_pricing_mode": "overage_above_default",
                "count_override_keys": ["exam_room_count", "exam_rooms_count"],
                "default_count_bands": [
                    {"label": "compact_urgent_care", "max_square_footage": 3000, "count": 6},
                    {"label": "small_urgent_care", "max_square_footage": 4500, "count": 8},
                    {"label": "standard_urgent_care", "max_square_footage": 6000, "count": 10},
                    {"label": "expanded_urgent_care", "max_square_footage": 7500, "count": 12},
                    {"label": "large_urgent_care", "max_square_footage": 9000, "count": 14},
                    {"label": "regional_urgent_care", "count": 18},
                ],
                "unit_label": "exam room",
            },
            "procedure_room": {
                "basis": "COUNT_BASED",
                "value": 175000,
                "count": 1,
                "count_override_keys": ["procedure_room_count"],
                "unit_label": "procedure room",
            },
            "trauma_room": {
                "basis": "COUNT_BASED",
                "value": 250000,
                "count": 1,
                "count_override_keys": ["trauma_room_count", "trauma_bay_count"],
                "unit_label": "room",
            },
            "x_ray": {
                "basis": "COUNT_BASED",
                "value": 250000,
                "count": 1,
                "count_pricing_mode": "overage_above_default",
                "count_override_keys": ["x_ray_room_count", "xray_room_count", "xray_count"],
                "unit_label": "x-ray room",
            },
            "laboratory": {
                "basis": "AREA_SHARE_GSF",
                "value": 20,
                "area_share_of_gsf": 0.05,
            },
            "pharmacy": {
                "basis": "AREA_SHARE_GSF",
                "value": 25,
                "area_share_of_gsf": 0.04,
            },
            "hc_urgent_on_site_lab": {
                "basis": "AREA_SHARE_GSF",
                "value": 38,
                "area_share_of_gsf": 0.08,
            },
            "hc_urgent_imaging_suite": {
                "basis": "COUNT_BASED",
                "value": 500000,
                "count": 1,
                "count_override_keys": ["urgent_imaging_suite_count", "imaging_suite_count"],
                "unit_label": "suite",
            },
            "hc_urgent_observation_bays": {
                "basis": "COUNT_BASED",
                "value": 50000,
                "count": 4,
                "count_override_keys": ["observation_bay_count", "observation_bays_count", "bay_count"],
                "unit_label": "bay",
            },
        },
        special_feature_pricing_statuses={
            "exam_rooms": "included_in_baseline",
            "procedure_room": "incremental",
            "trauma_room": "incremental",
            "x_ray": "included_in_baseline",
            "laboratory": "included_in_baseline",
            "pharmacy": "included_in_baseline",
            "hc_urgent_on_site_lab": "incremental",
            "hc_urgent_imaging_suite": "incremental",
            "hc_urgent_observation_bays": "incremental",
        },
        financial_metrics={
            "primary_unit": "exam rooms",
            "revenue_per_unit_annual": 180000,
            "target_occupancy": 0.75,
            "breakeven_occupancy": 0.65,
            "market_rate_type": "revenue_per_visit",
            "market_rate_default": 150,
            "display_name": "Per Exam Room Performance",
            "operational_metrics": {
                "throughput_per_unit_day": 13.0,
                "operating_days_per_year": 365,
                "utilization_target": 0.72,
                "provider_fte_per_unit": 0.33,
                "support_fte_per_provider": 1.2,
                "specialist_fte_per_unit": 0.08,
                "specialist_label": "On-Site Lab/Imaging FTE",
                "throughput_label": "Visits / Day",
                "utilization_label": "Exam Room Utilization",
                "efficiency_label": "Door-to-Provider Efficiency",
                "efficiency_green_threshold": 83.0,
                "efficiency_yellow_threshold": 67.0,
            },
        },
        base_revenue_per_sf_annual=430,
        base_revenue_per_visit=150,
        visits_per_day=50,
        days_per_year=365,
        occupancy_rate_base=0.70,
        occupancy_rate_premium=0.85,
        operating_margin_base=0.25,
        operating_margin_premium=0.30,
        labor_cost_ratio=0.40,
        supply_cost_ratio=0.12,
        management_fee_ratio=0.08,
        insurance_cost_ratio=0.03,
        utility_cost_ratio=0.03,
        maintenance_cost_ratio=0.03,
        marketing_ratio=0.03,
    ),
)
