from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.HEALTHCARE,
    "urgent_care",
    BuildingConfig(
        display_name="Urgent Care Center",
        base_cost_per_sf=350,
        cost_range=(400, 475),
        facility_metrics_profile="healthcare_outpatient",
        equipment_cost_per_sf=75,
        typical_floors=1,
        trades=TradeBreakdown(
            structural=0.26,
            mechanical=0.25,
            electrical=0.13,
            plumbing=0.14,
            finishes=0.22,
        ),
        soft_costs=SoftCosts(
            design_fees=0.06,
            permits=0.02,
            legal=0.015,
            financing=0.025,
            contingency=0.08,
            testing=0.01,
            construction_management=0.03,
            startup=0.015,
        ),
        ownership_types={
            OwnershipType.FOR_PROFIT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.065,
                equity_ratio=0.30,
                target_dscr=1.20,
                target_roi=0.11,
            )
        },
        nlp=NLPConfig(
            keywords=[
                "urgent care",
                "walk-in clinic",
                "immediate care",
                "express care",
                "quick care",
                "walk in",
            ],
            priority=3,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.95,
            "Memphis": 0.93,
            "New York": 1.25,
            "San Francisco": 1.30,
            "Chicago": 1.10,
            "Miami": 1.05,
        },
        special_features={
            "trauma_room": 30,
            "x_ray": 25,
            "laboratory": 20,
            "pharmacy": 25,
            "hc_urgent_on_site_lab": 38,
            "hc_urgent_imaging_suite": 75,
            "hc_urgent_observation_bays": 25,
        },
        financial_metrics={
            "primary_unit": "exam rooms",
            "units_per_sf": 1 / 450,
            "revenue_per_unit_annual": 180000,
            "target_occupancy": 0.75,
            "breakeven_occupancy": 0.65,
            "market_rate_type": "revenue_per_visit",
            "market_rate_default": 150,
            "display_name": "Per Exam Room Performance",
        },
        base_revenue_per_sf_annual=430,
        base_revenue_per_visit=150,
        visits_per_day=50,
        days_per_year=365,
        occupancy_rate_base=0.70,
        occupancy_rate_premium=0.85,
        operating_margin_base=0.25,
        operating_margin_premium=0.30,
        labor_cost_ratio=0.40,
        supply_cost_ratio=0.12,
        management_fee_ratio=0.08,
        insurance_cost_ratio=0.03,
        utility_cost_ratio=0.03,
        maintenance_cost_ratio=0.03,
        marketing_ratio=0.03,
    ),
)
