from app.v2.config.master_config import (
    BuildingType,
    BuildingConfig,
    TradeBreakdown,
    SoftCosts,
    FinancingTerms,
    OwnershipType,
    NLPConfig,
)


CONFIG = (
    BuildingType.CIVIC,
    "courthouse",
    BuildingConfig(
        display_name="Courthouse",
        base_cost_per_sf=325,
        cost_range=(300, 350),
        dealshield_tile_profile="civic_courthouse_v1",
        scope_items_profile="civic_courthouse_structural_v1",
        equipment_cost_per_sf=30,
        typical_floors=4,
        trades=TradeBreakdown(
            structural=0.28,  # Security requirements
            mechanical=0.24,
            electrical=0.16,
            plumbing=0.13,
            finishes=0.19,
        ),
        soft_costs=SoftCosts(
            design_fees=0.08,
            permits=0.015,
            legal=0.025,
            financing=0.025,
            contingency=0.09,
            testing=0.012,
            construction_management=0.04,
            startup=0.015,
        ),
        ownership_types={
            OwnershipType.GOVERNMENT: FinancingTerms(
                debt_ratio=0.70,
                debt_rate=0.038,
                equity_ratio=0.20,
                grants_ratio=0.10,
                target_dscr=1.15,
                target_roi=0.0,
            ),
            OwnershipType.NON_PROFIT: FinancingTerms(
                debt_ratio=0.60,
                debt_rate=0.045,
                equity_ratio=0.15,
                philanthropy_ratio=0.15,
                grants_ratio=0.10,
                target_dscr=1.10,
                target_roi=0.0,
            ),
        },
        nlp=NLPConfig(
            keywords=[
                "courthouse",
                "court house",
                "justice center",
                "judicial center",
                "court building",
                "federal court",
                "district court",
            ],
            priority=40,
            incompatible_classes=[],
        ),
        regional_multipliers={
            "Nashville": 1.03,
            "Franklin": 1.03,
            "Manchester": 0.94,
            "Memphis": 0.92,
            "New York": 1.42,
            "San Francisco": 1.45,
            "Chicago": 1.25,
            "Miami": 1.18,
        },
        special_features={
            "courtroom": {
                "basis": "AREA_SHARE_GSF",
                "value": 50,
                "area_share_of_gsf": 0.12,
            },
            "jury_room": {
                "basis": "AREA_SHARE_GSF",
                "value": 25,
                "area_share_of_gsf": 0.04,
            },
            "holding_cells": {
                "basis": "AREA_SHARE_GSF",
                "value": 40,
                "area_share_of_gsf": 0.03,
            },
            "judges_chambers": {
                "basis": "AREA_SHARE_GSF",
                "value": 30,
                "area_share_of_gsf": 0.05,
            },
            "security_screening": {
                "basis": "COUNT_BASED",
                "value": 180000,
                "count": 1,
                "count_override_keys": ["security_screening_count", "screening_checkpoint_count"],
                "unit_label": "checkpoint",
            },
            "magnetometer_screening_lanes": {
                "basis": "COUNT_BASED",
                "value": 35000,
                "count": 2,
                "count_override_keys": ["magnetometer_lane_count", "screening_lane_count", "lane_count"],
                "unit_label": "lane",
            },
            "sallyport": {
                "basis": "COUNT_BASED",
                "value": 300000,
                "count": 1,
                "count_override_keys": ["sallyport_count", "sally_port_count"],
                "unit_label": "port",
            },
            "ballistic_glazing_package": {
                "basis": "AREA_SHARE_GSF",
                "value": 30,
                "area_share_of_gsf": 0.08,
            },
            "redundant_life_safety_power": {
                "basis": "COUNT_BASED",
                "value": 500000,
                "count": 1,
                "count_override_keys": ["redundant_power_package_count", "life_safety_power_count"],
                "unit_label": "package",
            },
        },
        special_feature_pricing_statuses={
            "courtroom": "included_in_baseline",
            "jury_room": "included_in_baseline",
            "holding_cells": "included_in_baseline",
            "judges_chambers": "included_in_baseline",
            "security_screening": "included_in_baseline",
            "magnetometer_screening_lanes": "included_in_baseline",
            "sallyport": "included_in_baseline",
            "ballistic_glazing_package": "included_in_baseline",
            "redundant_life_safety_power": "incremental",
        },
        base_revenue_per_sf_annual=0,
        occupancy_rate_base=1.0,
        occupancy_rate_premium=1.0,
        operating_margin_base=0,
        operating_margin_premium=0,
    ),
)
